### ISSUE TITLE
Plugin working with an error window

### ISSUE THREAD

**Issue by Sillabix** [paulfioravanti/plover-cycle-translations#1]
With the selector stroke the cycle command works changing the current displayed definition but a windows pop up saying "ERROR:engine on_stroked failed ValueError: Text not cycleable or cycleable text needs to be re-stroked".

Plover version: 4.0.0rc2+6.g53c416f

**Comment by paulfioravanti** [comment]
Hi @Sillabix, I cannot seem to reproduce the issue that you are seeing using Plover 4.0.0rc2, so could you please let me know the following information:

- Plugin version
- Your OS/Platform
- Outline and translation that you stroked when you saw the error message come up
- The exact steps you performed before you saw the issue (a video/gif of the problem would help also if you're able to provide one)

**Comment by Sillabix** [comment]
Plugin version: 0.5.1
OS: Windows 10
Outline and translation (Michela system): "FPRen": "=CYCLE:treno,terreno"
Steps to perform: 1) write "FPRen" on the machine; 2) write the cycle stroke "Ff" (video attached

https://github.com/user-attachments/assets/080be02a-e1b7-440a-9198-76757d3ece3d

**Comment by paulfioravanti** [comment]
Given what I can see in the error message, it seems that it is occurring in the `_stroked` callback function. In that function, it is [assuming that the undo stroke is `*`](https://github.com/paulfioravanti/plover-cycle-translations/blob/40b468149266b06357df2a79b666f021d5e06a08/src/plover_cycle_translations/extension.py#L94), whereas it looks like you are using `U`. This is causing the `_translations` to not be reset when a stroke is not cycleable, and is likely the cause of this issue.

I admit that I only tested this out on a [WSI layout](https://plover.wiki/index.php/Ward_Stone_Ireland_layout), where undo is `*`, so it looks like I may have to enable customisation of that key to support layouts like Michela.

**Comment by paulfioravanti** [comment]
@Sillabix, I have just released [v0.5.2](https://github.com/paulfioravanti/plover-cycle-translations/releases/tag/v0.5.2) of the plugin with what I think will be a fix, so please try updating the plugin via the Plover plugins manager and give it a try.

**Comment by Sillabix** [comment]
Just tried. It works beautifully now. Thanks a lot for fixing it!
